name: Verificar Código JS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  lint:
    name: Validar JavaScript
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar ESLint
        run: npm install eslint --save-dev

      - name: Crear configuración ESLint
        run: |
          echo 'module.exports = {
            "env": { "browser": true, "es2021": true },
            "extends": "eslint:recommended",
            "parserOptions": { "ecmaVersion": 12, "sourceType": "module" },
            "rules": {}
          };' > .eslintrc.js

      - name: Ejecutar ESLint
        run: npx eslint index.js
