name: Verificar Código JS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Validar JavaScript
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Inicializar proyecto y ESLint
        run: |
          npm init -y
          npm install eslint --save-dev

      - name: Crear configuración ESLint (v9+)
        run: |
          echo 'export default [
            {
              files: ["**/*.js"],
              languageOptions: {
                ecmaVersion: 2021,
                sourceType: "module"
              },
              rules: {
                // Puedes agregar reglas personalizadas aquí
              }
            }
          ];' > eslint.config.js

      - name: Ejecutar ESLint
        run: npx eslint index.js




      - name: Ejecutar ESLint
        run: npx eslint index.js
